#!/usr/bin/env bash
# P1 recon: capture REAL `entire graph` / `entire checkpoint` output shapes for THIS repo.
# Run under Git Bash. Writes fixtures/*.json (real command output, raw) and NOTES.md
# (guess vs. truth for every command, plus errors verbatim). Never edit fixtures by hand.
set -uo pipefail

cd "$(dirname "$0")/.."
mkdir -p fixtures

NOTES=NOTES.md
DEF_TARGET="internal/sem/search.go:683"   # func SearchRepository(ctx, repo, providerVersion, query string, options SearchOptions)

: > "$NOTES"

log() { printf '%s\n' "$*" >> "$NOTES"; }

section() {
  log ""
  log "## $1"
  log ""
}

run() {
  # run "label" "guessed command" -- real command args...
  local label="$1" guess="$2"
  shift 2
  log "### $label"
  log ""
  log "guessed: \`$guess\`"
  log ""
  log "ran: \`$*\`"
  log ""
  log '```'
  "$@" >> "$NOTES" 2>&1
  local rc=$?
  log '```'
  log ""
  log "exit code: $rc"
  return 0
}

run_to_file() {
  # run_to_file "label" "guess" "fixture_path" -- real command args...
  local label="$1" guess="$2" fixture="$3"
  shift 3
  log "### $label"
  log ""
  log "guessed: \`$guess\`"
  log ""
  log "ran: \`$*\` > $fixture"
  log ""
  "$@" > "$fixture" 2>/tmp/recon-stderr.$$
  local rc=$?
  log '```'
  log "exit code: $rc"
  if [ -s "/tmp/recon-stderr.$$" ]; then
    log ""
    log "stderr:"
    log '```'
    cat "/tmp/recon-stderr.$$" >> "$NOTES"
    log '```'
  fi
  rm -f "/tmp/recon-stderr.$$"
  log ""
  log "fixture head (first 40 lines):"
  log '```json'
  head -n 40 "$fixture" >> "$NOTES" 2>&1
  log '```'
  log ""
}

log "# NOTES.md — real Entire CLI output shapes, captured on this machine"
log ""
log "Generated by \`scripts/recon.sh\`. Guessed commands are the ones written in"
log "the original design sketch, before the CLI was ever run. Real commands are what"
log "this clone actually accepts. Where they disagree, THIS FILE WINS — see CLAUDE.md."
log ""
log "entire version: \`$(entire version 2>&1 | tr '\n' ' ')\`"
log "entire graph version: \`$(entire graph version --json 2>&1 | tr '\n' ' ')\`"

section "1. entire graph --help"
run "top-level help" "(none guessed — discovered fresh)" entire graph --help

section "2. entire graph capabilities"
run_to_file "capabilities" "entire graph capabilities" fixtures/capabilities.json \
  entire graph capabilities --json

section "3. entire graph search"
run_to_file "search" 'entire graph search --query "..." --format json --top-k 8' fixtures/search.json \
  entire graph search --repo . --query "semantic search over a repository" --format json --top-k 8

section "4. entire graph def"
run_to_file "def" "entire graph def --symbol $DEF_TARGET --json" fixtures/def.json \
  entire graph def "$DEF_TARGET" --repo . --format json

section "5. entire graph impact"
run_to_file "impact" "entire graph impact --symbol SearchRepository --depth 2 --json" fixtures/impact.json \
  entire graph impact --symbol "$DEF_TARGET" --repo . --depth 2 --format json

section "6. entire checkpoint list"
run_to_file "checkpoint list" "entire checkpoint list --json" fixtures/checkpoints.json \
  entire checkpoint list --json

log ""
log "## Recon complete."
